name: Compilacion y Test

on:
  push:
    branches:
     - build-test
    paths-ignore:
#    - 'src/*'
     - 'package.json'
     - 'public/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build

      - name: Guardar build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  test:
    runs-on: ubuntu-latest  # Esto indica que se trata de una VM distinta a la del build
    needs: build  # Por default los jobs se ejecutan en paralelo, con esto indicamos que el test debe esperar a que termine el build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Descargar build
        uses: actions/download-artifact@v4
        with:
          name: build

      - run: npm install
      - run: npm test