name: Hola Mundo

on:
  workflow_dispatch:  # Se usa este evento para que el workflow se ejecute manualmente desde la interfaz de GitHub

jobs:
  build:  # El nombre del trabajo puede ser cualquier nombre descriptivo
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"